---
jobs:
  enforce:
    name: Enforce Repository Rulesets
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository
      # https://github.com/actions/checkout
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      # Set up uv
      # https://github.com/astral-sh/setup-uv
      - name: Set up uv
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
      # Execute the enforcement script
      - name: Execute enforcement script
        run: |
          uv run main.py \
            --debug \
            --exclude-required-check Analyze \
            --exclude-required-check dependency-review \
            --exclude-required-check "Create Draft Release" \
            --token ${{ secrets.GH_ENFORCE_PAT }} \
            --user MattKobayashi
name: Enforce Repository Rulesets
on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:
permissions:
  contents: read
