---
jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository
      # https://github.com/actions/checkout
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # Set up uv
      # https://github.com/astral-sh/setup-uv
      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      # Execute the enforcement script (dry-run)
      - name: Execute enforcement script (dry-run)
        run: |
          uv run main.py \
            --debug \
            --dry-run \
            --exclude-required-check Analyze \
            --exclude-required-check dependency-review \
            --exclude-required-check "Create Draft Release" \
            --token ${{ secrets.GH_ENFORCE_PAT }} \
            --user MattKobayashi
name: Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
