---
jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository
      # https://github.com/actions/checkout
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      # Set up uv
      # https://github.com/astral-sh/setup-uv
      - name: Set up uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
      # Execute the enforcement script (dry-run)
      - name: Execute enforcement script (dry-run)
        run: |
          uv run main.py \
            --debug \
            --dry-run \
            --exclude-required-check Analyze \
            --exclude-required-check dependency-review \
            --exclude-required-check "Create Draft Release" \
            --token ${{ secrets.GH_ENFORCE_PAT }} \
            --user MattKobayashi
name: Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
